#!/usr/bin/env bash
# One-time (idempotent) setup of PassVault on a shared Ubuntu host that already
# runs nginx, PostgreSQL and Docker (see docs/DEPLOYMENT.md, "Shared host").
#
#   sudo PV_DOMAIN=vault.example.com PV_API_PORT=3100 bash setup.sh
#
# What it does (re-running is safe; existing secrets are kept):
#   1. /opt/passvault/{.env,deploy.conf,releases,web,bin}; generates server secrets
#      (MFA key, recovery-code pepper, prelogin secret, DB password) — they never
#      leave this machine. SMTP must be filled in by hand afterwards.
#   2. PostgreSQL: role + database "passvault" (owned by the role), access only from
#      Docker networks (172.16.0.0/12) and localhost.
#   3. TLS certificate "passvault" from Let's Encrypt via certbot's nginx plugin
#      (auto-renewed by certbot.timer; nginx reloads after renewal).
#   4. nginx site for PV_DOMAIN: static web app + /api proxy to 127.0.0.1:PV_API_PORT.
#   5. /opt/passvault/bin/ci-deploy — the only command the CI deploy key may run.
set -euo pipefail
: "${PV_DOMAIN:?set PV_DOMAIN (the public host name)}"
PV_API_PORT="${PV_API_PORT:-3100}"
HERE="$(cd "$(dirname "$0")" && pwd)"
BASE=/opt/passvault
PG_VERSION="${PG_VERSION:-$(ls /etc/postgresql | sort -V | tail -1)}"
log() { printf '\n==> %s\n' "$*"; }

[[ $EUID -eq 0 ]] || { echo "run as root" >&2; exit 1; }
[[ "$PV_DOMAIN" =~ ^[a-z0-9.-]+$ ]] || { echo "invalid PV_DOMAIN" >&2; exit 1; }
[[ "$PV_API_PORT" =~ ^[0-9]+$ ]] || { echo "invalid PV_API_PORT" >&2; exit 1; }
if ss -tln | awk '{print $4}' | grep -q ":${PV_API_PORT}\$" && ! docker ps --format '{{.Names}}' | grep -q '^passvault-api'; then
  echo "port ${PV_API_PORT} is already used by another service; choose another PV_API_PORT" >&2
  exit 1
fi

log "Directories and secrets"
install -d -m 0755 "$BASE" "$BASE/releases" "$BASE/web" "$BASE/bin"
if [[ ! -f "$BASE/.env" ]]; then
  ( umask 077
    cat > "$BASE/.env" <<EOT
# PassVault API — production secrets (generated by setup.sh on $(date -u +%F)). Never commit or copy elsewhere.
DATABASE_URL=postgresql://passvault:$(openssl rand -hex 24)@host.docker.internal:5432/passvault
MFA_ENCRYPTION_KEY=$(openssl rand -base64 32)
RECOVERY_CODE_PEPPER=$(openssl rand -base64 32)
PRELOGIN_SECRET=$(openssl rand -base64 32)
WEB_APP_URL=https://${PV_DOMAIN}
# web dashboard + macOS desktop app (Neutralino serves its UI from this fixed origin)
CORS_ORIGINS=https://${PV_DOMAIN},http://localhost:47391
MAIL_FROM=PassVault <no-reply@${PV_DOMAIN}>
# SMTP provider — REQUIRED for registration codes and recovery links. Until it is set,
# the API runs but cannot send email (sign-ups cannot complete).
SMTP_HOST=smtp.invalid
SMTP_PORT=587
SMTP_SECURE=false
SMTP_REQUIRE_TLS=true
SMTP_USER=
SMTP_PASSWORD=
LOG_LEVEL=info
EOT
  )
  echo "created $BASE/.env (0600)"
else
  echo "$BASE/.env exists — kept"
fi
chmod 600 "$BASE/.env"
cat > "$BASE/deploy.conf" <<EOT
PV_DOMAIN=${PV_DOMAIN}
PV_API_PORT=${PV_API_PORT}
EOT

log "PostgreSQL ${PG_VERSION}: role and database"
DBPASS="$(sed -n 's#^DATABASE_URL=postgresql://passvault:\([^@]*\)@.*#\1#p' "$BASE/.env")"
[[ "$DBPASS" =~ ^[a-f0-9]{48}$ ]] || { echo "unexpected DATABASE_URL format in $BASE/.env" >&2; exit 1; }
# Password via stdin (never on a command line).
sudo -u postgres psql -v ON_ERROR_STOP=1 -q <<SQL
SELECT 'CREATE ROLE passvault LOGIN' WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'passvault')\gexec
ALTER ROLE passvault WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD '${DBPASS}';
SELECT 'CREATE DATABASE passvault OWNER passvault' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'passvault')\gexec
REVOKE ALL ON DATABASE passvault FROM PUBLIC;
SQL
HBA="/etc/postgresql/${PG_VERSION}/main/pg_hba.conf"
LINE="host    passvault       passvault       172.16.0.0/12           scram-sha-256"
grep -qF "$LINE" "$HBA" || { echo "$LINE" >> "$HBA"; echo "pg_hba: added Docker-network rule for passvault"; }
systemctl reload "postgresql@${PG_VERSION}-main"

log "TLS certificate (Let's Encrypt)"
install -d -m 0755 /var/www/letsencrypt
if [[ ! -f /etc/letsencrypt/live/passvault/fullchain.pem ]]; then
  certbot certonly --nginx --non-interactive --agree-tos --cert-name passvault -d "$PV_DOMAIN" \
    --deploy-hook 'systemctl reload nginx'
else
  echo "certificate 'passvault' exists — renewal is handled by certbot.timer"
fi

log "nginx site"
install -m 0644 "$HERE/nginx-headers.conf" /etc/nginx/snippets/passvault-headers.conf
if [[ ! -e "$BASE/web/current" ]]; then
  install -d -m 0755 "$BASE/web/placeholder"
  echo '<!doctype html><title>PassVault</title><p>PassVault is being deployed.</p>' > "$BASE/web/placeholder/index.html"
  ln -sfn "$BASE/web/placeholder" "$BASE/web/current"
fi
PV_WEB_ROOT="$BASE/web/current" PV_DOMAIN="$PV_DOMAIN" PV_API_PORT="$PV_API_PORT" \
  envsubst '${PV_DOMAIN} ${PV_API_PORT} ${PV_WEB_ROOT}' < "$HERE/nginx.conf.template" > /etc/nginx/sites-available/passvault.conf
ln -sfn /etc/nginx/sites-available/passvault.conf /etc/nginx/sites-enabled/passvault.conf
nginx -t
systemctl reload nginx

log "CI deploy command"
install -m 0755 "$HERE/ci-deploy.sh" "$BASE/bin/ci-deploy"
install -m 0644 "$HERE/compose.yaml" "$BASE/compose.yaml"

log "Done"
echo "Next: deploy a release (GitHub Actions 'Deploy' workflow, or bin/ci-deploy locally),"
echo "then set SMTP_* in $BASE/.env and run: $BASE/bin/ci-deploy restart"
